creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        #anderer (Ich)
        - age1grgn2qn6ajs6n64q5rnwg8nna0v8a3lzgrvaezp9xjcv675cuqhsthfta5
        #trolllollo (Rechner)
        - age1u6s4rlxc9mjm9d077qkvxakk6drpyrxpm0sfye286whnv4vywa5qyu3pqn
  - path_regex: trolllollo\.yaml$
    key_groups:
      - age:
        #anderer (Ich)
        - age1grgn2qn6ajs6n64q5rnwg8nna0v8a3lzgrvaezp9xjcv675cuqhsthfta5
        #trolllollo (Rechner)
        - age1u6s4rlxc9mjm9d077qkvxakk6drpyrxpm0sfye286whnv4vywa5qyu3pqn