name: Flake Checks
on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
      - name: Run flake checks
        run: nix develop -c nix-fast-build --no-nom --no-download
